services:
  solver:
    build: 
      args:
        - FLASK_DEBUG=false
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: 3s
    deploy:
      # resources:
      #   limits:
      #     cpus: "${DOCKER_WEB_CPUS:-0}"
      #     memory: "${DOCKER_WEB_MEMORY:-0}"
      replicas: 2
    ports:
      - "8000"
    
    # healthcheck:
    #   test: "${DOCKER_WEB_HEALTHCHECK_TEST:-curl localhost:8000/up}"
    #   interval: "60s"
    #   timeout: "3s"
    #   start_period: "5s"
    #   retries: 3

  rproxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - flask_net
    depends_on:
      # does not work with stack deploy
      - solver
    ports:
      - "4000:4000"